// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package client

// EndTS defines model for endTS.
type EndTS string

// Query defines model for query.
type Query string

// QueryTimeout defines model for queryTimeout.
type QueryTimeout string

// SeriesMatcher defines model for seriesMatcher.
type SeriesMatcher []string

// StartTS defines model for startTS.
type StartTS string

// Tenant defines model for tenant.
type Tenant string
