version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  allowed_updates:
  - match:
      dependency-name: "k8s.io/api"
      update-type: "semver-patch"
  - match:
      dependency-name: "k8s.io/apimachinery"
      update-type: "semver-patch"
  - match:
      dependency-name: "k8s.io/apiserver"
      update-type: "semver-patch"
  - match:
      dependency-name: "k8s.io/client-go"
      update-type: "semver-patch"
