run:
  # default concurrency is a available CPU number
  concurrency: 4
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 3m
  tests: true

linters-settings:
  errcheck:
    exclude: .errcheck_excludes
  lll:
    line-length: 160
  funlen:
    lines: 140
    statements: 60
