version: "2"
run:
  concurrency: 4
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - copyloopvar
    - goconst
    - godot
    - misspell # spell checker
    - promlinter
    - unparam
    - forbidigo
  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - fmt.Fprintln
        - fmt.Fprint
    funlen:
      lines: 140
      statements: 60
    goconst:
      min-occurrences: 5
    lll:
      line-length: 160
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci # Gci controls Go package import order and makes it always deterministic
    - gofumpt # checks that gofumpt was run on all source code
    - goimports # checks that goimports was run on all source code
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/observatorium/api)
        - blank
        - dot
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
