// Code generated by goyacc -p expr -o logql/v2/expr.y.go logql/v2/expr.y. DO NOT EDIT.

package v2

import (
	__yyfmt__ "fmt"
	"time"

	"github.com/prometheus/prometheus/model/labels"
)

type exprSymType struct {
	yys                int
	Expr               Expr
	LogBinaryOpExpr    LogBinaryOpExpr
	LogFilterExpr      *LogFilterExpr
	LogLabelFilterExpr *LogLabelFilterExpr
	LogFormatExpr      *LogFormatExpr
	LogQueryExpr       LogSelectorExpr
	LogMetricExpr      LogMetricSampleExpr
	LogNumberExpr      LogNumberExpr
	LogPipelineExpr    LogPipelineExpr
	LogStageExpr       LogStageExpr
	LogRangeQueryExpr  LogSelectorExpr
	LogOffsetExpr      *LogOffsetExpr
	LogDropLabels      LogLabelList
	LogFMTLabels       LogLabelList
	Matcher            *labels.Matcher
	Matchers           []*labels.Matcher
	MetricOp           string
	BinaryOpOptions    BinaryOpOptions
	Range              string
	Filter             string
	Selector           []*labels.Matcher
	Grouping           *grouping
	Labels             []string
	str                string
	binaryOp           string
	ComparisonOp       string
	duration           time.Duration
	ConvOp             string
}

const IDENTIFIER = 57346
const STRING = 57347
const RANGE = 57348
const NUMBER = 57349
const DURATION = 57350
const MATCHERS = 57351
const LABELS = 57352
const EQ = 57353
const RE = 57354
const NRE = 57355
const OPEN_BRACE = 57356
const CLOSE_BRACE = 57357
const OPEN_BRACKET = 57358
const CLOSE_BRACKET = 57359
const COMMA = 57360
const DOT = 57361
const OPEN_PARENTHESIS = 57362
const CLOSE_PARENTHESIS = 57363
const COUNT_OVER_TIME = 57364
const RATE = 57365
const RATE_COUNTER = 57366
const SUM = 57367
const AVG = 57368
const MAX = 57369
const MIN = 57370
const COUNT = 57371
const STDDEV = 57372
const STDVAR = 57373
const BOTTOMK = 57374
const TOPK = 57375
const SORT = 57376
const SORT_DESC = 57377
const BYTES_OVER_TIME = 57378
const BYTES_RATE = 57379
const BOOL = 57380
const JSON = 57381
const REGEXP = 57382
const LOGFMT = 57383
const PIPE_MATCH = 57384
const PIPE_EXACT = 57385
const PIPE = 57386
const LINE_FMT = 57387
const LABEL_FMT = 57388
const UNWRAP = 57389
const AVG_OVER_TIME = 57390
const SUM_OVER_TIME = 57391
const MIN_OVER_TIME = 57392
const MAX_OVER_TIME = 57393
const STDVAR_OVER_TIME = 57394
const STDDEV_OVER_TIME = 57395
const QUANTILE_OVER_TIME = 57396
const FIRST_OVER_TIME = 57397
const LAST_OVER_TIME = 57398
const ABSENT_OVER_TIME = 57399
const BY = 57400
const WITHOUT = 57401
const VECTOR = 57402
const LABEL_REPLACE = 57403
const IP = 57404
const UNPACK = 57405
const PATTERN = 57406
const OFFSET = 57407
const BYTES_CONV = 57408
const DURATION_CONV = 57409
const DURATION_SECONDS_CONV = 57410
const ON = 57411
const IGNORING = 57412
const GROUP_LEFT = 57413
const GROUP_RIGHT = 57414
const DECOLORIZE = 57415
const DROP = 57416
const OR = 57417
const AND = 57418
const UNLESS = 57419
const CMP_EQ = 57420
const NEQ = 57421
const LT = 57422
const LTE = 57423
const GT = 57424
const GTE = 57425
const ADD = 57426
const SUB = 57427
const MUL = 57428
const DIV = 57429
const MOD = 57430
const POW = 57431

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"RANGE",
	"NUMBER",
	"DURATION",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"COUNT_OVER_TIME",
	"RATE",
	"RATE_COUNTER",
	"SUM",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"SORT",
	"SORT_DESC",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"FIRST_OVER_TIME",
	"LAST_OVER_TIME",
	"ABSENT_OVER_TIME",
	"BY",
	"WITHOUT",
	"VECTOR",
	"LABEL_REPLACE",
	"IP",
	"UNPACK",
	"PATTERN",
	"OFFSET",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"ON",
	"IGNORING",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"DECOLORIZE",
	"DROP",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16

var exprExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 654

var exprAct = [...]int{
	190, 69, 58, 57, 178, 4, 161, 5, 163, 96,
	151, 112, 165, 7, 67, 3, 118, 2, 45, 46,
	47, 48, 49, 50, 66, 50, 80, 77, 42, 43,
	44, 51, 52, 55, 56, 53, 54, 45, 46, 47,
	48, 49, 50, 43, 44, 51, 52, 55, 56, 53,
	54, 45, 46, 47, 48, 49, 50, 337, 64, 150,
	95, 51, 52, 55, 56, 53, 54, 45, 46, 47,
	48, 49, 50, 213, 114, 108, 115, 254, 122, 150,
	123, 336, 116, 47, 48, 49, 50, 62, 63, 60,
	290, 291, 313, 167, 169, 170, 131, 229, 134, 135,
	136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
	146, 147, 70, 71, 127, 129, 130, 148, 286, 287,
	184, 179, 193, 67, 65, 188, 295, 189, 270, 271,
	214, 186, 109, 66, 14, 153, 149, 148, 283, 197,
	8, 179, 15, 16, 17, 30, 31, 33, 34, 32,
	35, 36, 37, 38, 39, 40, 18, 19, 204, 205,
	206, 168, 173, 174, 171, 172, 267, 268, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 282, 216,
	41, 10, 128, 64, 222, 223, 220, 95, 221, 225,
	226, 281, 219, 230, 116, 246, 245, 155, 156, 157,
	278, 176, 232, 237, 239, 333, 276, 272, 64, 68,
	329, 262, 62, 63, 60, 64, 258, 244, 241, 251,
	252, 248, 176, 257, 253, 255, 192, 232, 95, 95,
	332, 259, 232, 227, 260, 331, 261, 62, 63, 60,
	64, 177, 192, 324, 62, 63, 60, 70, 71, 65,
	192, 256, 232, 247, 275, 330, 277, 232, 279, 322,
	327, 250, 95, 232, 179, 232, 326, 318, 321, 62,
	63, 60, 232, 232, 65, 320, 269, 231, 296, 192,
	297, 65, 217, 298, 192, 179, 183, 182, 232, 304,
	306, 266, 224, 310, 312, 111, 316, 11, 185, 64,
	110, 311, 317, 319, 14, 64, 65, 308, 323, 325,
	8, 307, 15, 16, 17, 30, 31, 33, 34, 32,
	35, 36, 37, 38, 39, 40, 18, 19, 62, 63,
	60, 192, 192, 302, 62, 63, 60, 192, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 309, 305,
	41, 10, 192, 232, 303, 192, 234, 301, 232, 132,
	133, 233, 293, 11, 180, 65, 211, 181, 328, 240,
	14, 65, 238, 292, 12, 13, 8, 192, 15, 16,
	17, 30, 31, 33, 34, 32, 35, 36, 37, 38,
	39, 40, 18, 19, 194, 289, 288, 192, 273, 249,
	209, 203, 202, 175, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 191, 125, 41, 10, 121, 120,
	119, 72, 300, 299, 212, 210, 207, 265, 124, 11,
	264, 126, 150, 228, 196, 195, 14, 208, 218, 74,
	12, 13, 117, 73, 15, 16, 17, 30, 31, 33,
	34, 32, 35, 36, 37, 38, 39, 40, 18, 19,
	280, 335, 334, 315, 314, 294, 285, 284, 274, 78,
	20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
	76, 242, 41, 10, 236, 235, 215, 201, 200, 199,
	198, 160, 159, 154, 158, 187, 263, 164, 162, 243,
	152, 107, 14, 78, 9, 75, 12, 13, 8, 6,
	15, 16, 17, 30, 31, 33, 34, 32, 35, 36,
	37, 38, 39, 40, 18, 19, 59, 61, 166, 1,
	0, 0, 0, 0, 0, 0, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 0, 0, 41, 10,
	0, 0, 0, 0, 0, 0, 0, 107, 0, 0,
	0, 113, 0, 0, 0, 0, 0, 0, 14, 0,
	0, 0, 12, 13, 117, 0, 15, 16, 17, 30,
	31, 33, 34, 32, 35, 36, 37, 38, 39, 40,
	18, 19, 98, 101, 97, 0, 79, 0, 103, 105,
	100, 0, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 0, 0, 41, 10, 99, 102, 0, 0,
	0, 0, 0, 0, 0, 0, 104, 106, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 12, 13,
	81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
	91, 92, 93, 94,
}

var exprPact = [...]int{
	356, -1000, -47, -1000, -1000, -1000, -1000, 45, 120, 189,
	401, -1000, 436, 432, 465, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -12, -12, -12, -12, -12, -12, -12, -12,
	-12, -12, -12, -12, -12, -12, -12, 45, -1000, -1000,
	553, 70, -1000, -1000, -1000, -1000, 279, 274, 554, 400,
	399, 398, 356, -1000, -1000, 413, -1000, -1000, 103, 290,
	-1000, 290, 290, 290, 290, 290, 290, 290, 290, 290,
	290, 290, 290, 290, 290, -1000, 61, 496, -1000, -1000,
	131, 489, 487, 486, -1000, 494, 493, 82, -1000, 383,
	-1000, -1000, 220, 346, 266, 265, 292, 120, -47, 488,
	393, 373, 417, 416, -1000, -1000, 499, 485, 484, 483,
	482, -33, 382, 381, -17, -17, -3, -3, -64, -64,
	-64, -64, -66, -66, -66, -66, -66, -66, 497, 497,
	497, 408, 426, -1000, 380, -1000, -1000, -1000, -1000, -1000,
	-1000, 407, 355, 406, 103, -1000, 68, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 481, -1000, 54, 261, 430,
	422, -1000, 54, 54, 286, 45, 227, 415, 76, 256,
	340, -1000, -1000, 335, -1000, 480, 479, -1000, -1000, -1000,
	-1000, -1000, 351, 348, 414, 41, 61, 496, 476, 495,
	494, 191, 493, -1000, 379, 240, -1000, 54, -1000, 199,
	56, 230, -1000, -1000, -1000, 45, 202, 195, 356, -1000,
	190, -1000, 492, -1000, -1000, 412, 409, 270, 95, 255,
	57, 408, -1000, 186, 407, -1000, -1000, 378, 406, 463,
	-1000, -1000, 54, 185, 54, 179, 54, 454, -1000, 170,
	157, 117, -1000, -1000, 462, 461, 47, 376, 375, 19,
	353, 342, -1000, 460, 105, -1000, 54, -1000, 54, -1000,
	-1000, 54, -1000, -1000, 405, 404, 337, 313, 333, 328,
	291, 287, 327, 280, 71, -1000, -1000, -1000, -1000, 459,
	458, 275, 246, -1000, 254, -1000, 247, 238, 222, -1000,
	245, -1000, 239, -1000, 350, 192, -1000, 234, -1000, 214,
	-1000, -1000, -1000, 209, -1000, 184, -1000, -1000, 457, 456,
	-1000, -1000, -1000, -1000, 60, 36, -1000, -1000,
}

var exprPgo = [...]int{
	0, 529, 596, 528, 16, 527, 0, 7, 526, 9,
	6, 15, 5, 509, 3, 2, 11, 4, 8, 10,
	12, 505, 504, 13, 1, 493,
}

var exprR1 = [...]int{
	0, 1, 4, 4, 4, 4, 11, 11, 11, 14,
	14, 25, 25, 25, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 15, 15, 8, 8,
	9, 9, 9, 9, 9, 10, 10, 10, 10, 17,
	16, 16, 16, 16, 16, 16, 16, 16, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 13,
	13, 13, 18, 18, 18, 19, 19, 19, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	23, 23, 23, 21, 21, 20, 20, 20, 20, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 5, 5, 5, 5,
	3, 3, 3, 3, 3, 3, 3, 3, 6, 6,
	24, 24, 24, 24,
}

var exprR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 2, 3, 1,
	2, 1, 1, 1, 1, 2, 2, 3, 2, 2,
	3, 6, 3, 3, 3, 2, 3, 3, 2, 5,
	3, 6, 3, 3, 3, 3, 3, 6, 3, 2,
	2, 3, 3, 4, 5, 5, 6, 2, 4, 5,
	6, 7, 7, 8, 5, 6, 5, 4, 6, 7,
	8, 7, 5, 6, 12, 5, 4, 6, 7, 7,
	5, 12, 4, 3, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 4, 1,
	2, 2, 1, 1, 3, 1, 3, 3, 0, 1,
	5, 8, 9, 8, 9, 4, 7, 8, 7, 8,
	5, 8, 9, 8, 9, 4, 7, 8, 7, 8,
	3, 3, 2, 1, 3, 3, 3, 3, 3, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	4, 4, 3, 3,
}

var exprChk = [...]int{
	-1000, -1, -4, -11, -12, -7, -13, -23, 20, -22,
	61, 7, 84, 85, 14, 22, 23, 24, 36, 37,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	25, 26, 29, 27, 28, 30, 31, 32, 33, 34,
	35, 60, 75, 76, 77, 84, 85, 86, 87, 88,
	89, 78, 79, 82, 83, 80, 81, -14, -15, -8,
	44, -5, 42, 43, 13, 79, -11, -12, 20, -24,
	58, 59, 20, 7, 7, -21, 15, -20, 4, -2,
	38, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -15, -9, 41, 39, 63,
	47, 40, 64, 45, 73, 46, 74, 4, 5, 62,
	21, 21, -16, 7, -12, -7, -23, 20, -4, 20,
	20, 20, -12, -7, 15, 2, 18, 11, 79, 12,
	13, -4, 69, 70, -4, -4, -4, -4, -4, -4,
	-4, -4, -4, -4, -4, -4, -4, -4, 76, 75,
	18, -19, 4, 4, -25, 66, 67, 68, 5, 5,
	5, -10, 4, -18, 4, -20, -3, 11, 79, 12,
	13, 82, 83, 80, 81, 20, 2, 21, -17, 65,
	18, 21, 21, 21, -14, 6, -23, 7, -12, -7,
	-6, 21, 4, -6, 21, 18, 18, -20, 5, 5,
	5, 5, 20, 20, -9, -9, -9, 18, 11, 20,
	18, 11, 18, 5, 62, 5, -24, 21, 8, -16,
	-12, -7, -24, -24, 6, -14, -14, 6, 18, 21,
	-17, 21, 18, 21, 21, 5, 5, -6, 21, -6,
	21, -19, 5, 4, -10, 5, 4, 62, -18, 20,
	21, -24, 21, -17, 21, -17, 21, 21, 21, -14,
	-12, -7, 21, 4, 18, 18, 21, 71, 72, 21,
	71, 72, 21, 20, 5, -24, 21, -24, 21, -24,
	6, 21, 21, 21, 5, 5, 71, 72, 20, 20,
	71, 72, 20, 20, 5, 21, -24, -24, -24, 18,
	18, 20, 20, 21, -6, 21, -6, 20, 20, 21,
	-6, 21, -6, 21, 5, 5, 21, -6, 21, -6,
	21, 21, 21, -6, 21, -6, 21, 21, 18, 18,
	21, 21, 21, 21, 5, 5, 21, 21,
}

var exprDef = [...]int{
	0, -2, 1, 2, 3, 4, 5, 6, 0, 0,
	0, 89, 0, 0, 0, 129, 130, 131, 132, 133,
	134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
	144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
	154, 155, 98, 98, 98, 98, 98, 98, 98, 98,
	98, 98, 98, 98, 98, 98, 98, 7, 9, 14,
	0, 0, 156, 157, 158, 159, 0, 0, 0, 0,
	0, 0, 0, 90, 91, 0, 122, 123, 0, 0,
	99, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 10, 15, 16, 18, 19,
	0, 0, 0, 0, 25, 0, 0, 0, 28, 0,
	8, 73, 0, 89, 3, 4, 6, 0, 0, 0,
	0, 0, 3, 4, 120, 121, 0, 0, 0, 0,
	0, 74, 0, 0, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 88, 0, 0,
	0, 17, 95, 20, 0, 11, 12, 13, 22, 23,
	24, 26, 0, 27, 92, 93, 0, 160, 161, 162,
	163, 164, 165, 166, 167, 0, 47, 48, 0, 0,
	0, 72, 57, 66, 7, 40, 6, 89, 3, 4,
	0, 172, 168, 0, 173, 0, 0, 124, 125, 126,
	127, 128, 0, 0, 32, 33, 34, 0, 0, 0,
	0, 0, 0, 30, 0, 0, 54, 49, 39, 0,
	3, 4, 56, 65, 42, 41, 0, 0, 0, 62,
	0, 70, 0, 170, 171, 0, 0, 0, 105, 0,
	115, 97, 96, 0, 38, 35, 36, 0, 94, 0,
	29, 55, 50, 0, 58, 0, 67, 0, 43, 0,
	3, 4, 63, 169, 0, 0, 100, 0, 0, 110,
	0, 0, 21, 0, 0, 51, 52, 59, 0, 68,
	45, 44, 61, 69, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 31, 53, 60, 46, 0,
	0, 0, 0, 106, 0, 108, 0, 0, 0, 116,
	0, 118, 0, 37, 0, 0, 101, 0, 103, 0,
	107, 109, 111, 0, 113, 0, 117, 119, 0, 0,
	102, 104, 112, 114, 0, 0, 64, 71,
}

var exprTok1 = [...]int{
	1,
}

var exprTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89,
}

var exprTok3 = [...]int{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := exprPact[state]
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && exprChk[exprAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || exprExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := exprExca[i]
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = exprTok1[0]
		goto out
	}
	if char < len(exprTok1) {
		token = exprTok1[char]
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = exprTok2[char-exprPrivate]
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = exprTok3[i+0]
		if token == char {
			token = exprTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = exprTok2[1] /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = exprPact[exprstate]
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = exprAct[exprn]
	if exprChk[exprn] == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = exprDef[exprstate]
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && exprExca[xi+1] == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = exprExca[xi+0]
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = exprExca[xi+1]
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = exprPact[exprS[exprp].yys] + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = exprAct[exprn] /* simulate a shift of "error" */
					if exprChk[exprstate] == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= exprR2[exprn]
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = exprR1[exprn]
	exprg := exprPgo[exprn]
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = exprAct[exprg]
	} else {
		exprstate = exprAct[exprj]
		if exprChk[exprstate] != -exprn {
			exprstate = exprAct[exprg]
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprlex.(*parser).expr = exprDollar[1].Expr
		}
	case 2:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogQueryExpr
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogMetricExpr
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogBinaryOpExpr
		}
	case 5:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogNumberExpr
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogQueryExpr = newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), nil)
		}
	case 7:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogQueryExpr = newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[2].LogPipelineExpr)
		}
	case 8:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogQueryExpr = exprDollar[2].LogQueryExpr
		}
	case 9:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogPipelineExpr = LogPipelineExpr{exprDollar[1].LogStageExpr}
		}
	case 10:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogPipelineExpr = append(exprDollar[1].LogPipelineExpr, exprDollar[2].LogStageExpr)
		}
	case 11:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvBytes
		}
	case 12:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDuration
		}
	case 13:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDurationSeconds
		}
	case 14:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[1].LogFilterExpr
		}
	case 15:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[2].LogLabelFilterExpr
		}
	case 16:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserLogFMT, "", "")
		}
	case 17:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogLabelExpr(ParserLogFMT, exprDollar[3].LogFMTLabels)
		}
	case 18:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserJSON, "", "")
		}
	case 19:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnpack, "", "")
		}
	case 20:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnwrap, exprDollar[3].str, "")
		}
	case 21:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnwrap, exprDollar[5].str, exprDollar[3].ConvOp)
		}
	case 22:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserRegExp, exprDollar[3].str, "")
		}
	case 23:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserPattern, exprDollar[3].str, "")
		}
	case 24:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserLineFormat, exprDollar[3].str, "")
		}
	case 25:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogDecolorizeExpr()
		}
	case 26:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[3].LogFormatExpr
		}
	case 27:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogLabelExpr(ParserDrop, exprDollar[3].LogDropLabels)
		}
	case 28:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogFilterExpr = newLogFilterExpr(exprDollar[1].Filter, "", exprDollar[2].str)
		}
	case 29:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogFilterExpr = newLogFilterExpr(exprDollar[1].Filter, OpIP, exprDollar[4].str)
		}
	case 30:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = newLogLabelFilter(exprDollar[1].str, exprDollar[2].ComparisonOp, "", exprDollar[3].str)
		}
	case 31:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = newLogLabelFilter(exprDollar[1].str, exprDollar[2].ComparisonOp, OpIP, exprDollar[5].str)
		}
	case 32:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain("and", exprDollar[3].LogLabelFilterExpr)
		}
	case 33:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain("or", exprDollar[3].LogLabelFilterExpr)
		}
	case 34:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain(",", exprDollar[3].LogLabelFilterExpr)
		}
	case 35:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: exprDollar[3].str}}, "")
		}
	case 36:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: exprDollar[3].str, IsIdentifier: true}}, "")
		}
	case 37:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: OpIP + "(" + exprDollar[5].str + ")"}}, "")
		}
	case 38:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr(",", mergeLogFormatValues(exprDollar[1].LogFormatExpr.kv, exprDollar[3].LogFormatExpr.kv), "")
		}
	case 39:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogOffsetExpr = newLogOffsetExpr(exprDollar[2].duration)
		}
	case 40:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), nil), exprDollar[2].str, nil, false)
		}
	case 41:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[3].LogPipelineExpr), exprDollar[2].str, nil, false)
		}
	case 42:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[2].LogPipelineExpr), exprDollar[3].str, nil, true)
		}
	case 43:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), nil), exprDollar[3].str, nil, false)
		}
	case 44:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[4].LogPipelineExpr), exprDollar[3].str, nil, false)
		}
	case 45:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[3].LogPipelineExpr), exprDollar[5].str, nil, true)
		}
	case 46:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[4].LogPipelineExpr), exprDollar[3].str, exprDollar[6].Grouping, false)
		}
	case 48:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 49:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, exprDollar[1].MetricOp, "", nil, false, nil, exprDollar[4].LogOffsetExpr)
		}
	case 50:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 51:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 52:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 53:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[8].Grouping, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 54:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, "", "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 55:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, "", "", exprDollar[6].Grouping, false, nil, exprDollar[4].LogOffsetExpr)
		}
	case 56:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 57:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 58:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 59:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 60:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[8].Grouping, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 61:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[6].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[4].str, exprDollar[2].Grouping, true, nil, nil)
		}
	case 62:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, nil)
		}
	case 63:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, exprDollar[5].LogOffsetExpr)
		}
	case 64:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, OpLabelReplace, "", nil, false, []string{exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str}, nil)
		}
	case 65:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 66:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 67:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 68:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 69:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[6].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[4].str, exprDollar[2].Grouping, true, nil, nil)
		}
	case 70:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, nil)
		}
	case 71:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, OpLabelReplace, "", nil, false, []string{exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str}, nil)
		}
	case 72:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(newVectorExpr(exprDollar[3].str), nil, OpTypeVector, "", nil, false, nil, nil)
		}
	case 73:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogMetricExpr = exprDollar[2].LogMetricExpr
		}
	case 74:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("or", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 75:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("and", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 76:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("unless", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 77:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("+", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 78:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("-", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 79:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("*", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 80:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("/", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 81:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("%", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 82:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("^", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 83:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("==", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 84:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("!=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 85:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr(">", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 86:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr(">=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 87:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("<", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 88:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("<=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 89:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[1].str, false)
		}
	case 90:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[2].str, false)
		}
	case 91:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[2].str, true)
		}
	case 92:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogDropLabels = newLogLabelList(newLogLabel(exprDollar[1].str, nil))
		}
	case 93:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogDropLabels = newLogLabelList(newLogLabel("", exprDollar[1].Matcher))
		}
	case 94:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogDropLabels = mergeLabels(exprDollar[1].LogDropLabels, exprDollar[3].LogDropLabels)
		}
	case 95:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogFMTLabels = newLogLabelList(newLogLabel(exprDollar[1].str, nil))
		}
	case 96:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFMTLabels = newLogLabelList(newLogLabel("", newLabelMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)))
		}
	case 97:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFMTLabels = mergeLabels(exprDollar[1].LogFMTLabels, exprDollar[3].LogFMTLabels)
		}
	case 98:
		exprDollar = exprS[exprpt-0 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = BinaryOpOptions{}
		}
	case 99:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = BinaryOpOptions{ReturnBool: true}
		}
	case 100:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels}
		}
	case 101:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption}
		}
	case 102:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 103:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption}
		}
	case 104:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 105:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true}
		}
	case 106:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupLeftOption}
		}
	case 107:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 108:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupRightOption}
		}
	case 109:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupRightOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 110:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels}
		}
	case 111:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption}
		}
	case 112:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 113:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption}
		}
	case 114:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 115:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true}
		}
	case 116:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupLeftOption}
		}
	case 117:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 118:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupRightOption}
		}
	case 119:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupRightOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 120:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 121:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 122:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
		}
	case 123:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Matchers = []*labels.Matcher{exprDollar[1].Matcher}
		}
	case 124:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matchers = append(exprDollar[1].Matchers, exprDollar[3].Matcher)
		}
	case 125:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 126:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchNotEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 127:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 128:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchNotRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 129:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeCount
		}
	case 130:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeRate
		}
	case 131:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeRateCounter
		}
	case 132:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeBytes
		}
	case 133:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeBytesRate
		}
	case 134:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeAvg
		}
	case 135:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeSum
		}
	case 136:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeMin
		}
	case 137:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeMax
		}
	case 138:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeStdvar
		}
	case 139:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeStddev
		}
	case 140:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeQuantile
		}
	case 141:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeFirst
		}
	case 142:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeLast
		}
	case 143:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeAbsent
		}
	case 144:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSum
		}
	case 145:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeAvg
		}
	case 146:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeCount
		}
	case 147:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeMax
		}
	case 148:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeMin
		}
	case 149:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeStddev
		}
	case 150:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeStdvar
		}
	case 151:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeBottomK
		}
	case 152:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeTopK
		}
	case 153:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSort
		}
	case 154:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSortDesc
		}
	case 155:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = OpTypeVector
		}
	case 156:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "|~"
		}
	case 157:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "|="
		}
	case 158:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "!~"
		}
	case 159:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "!="
		}
	case 160:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "="
		}
	case 161:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "!="
		}
	case 162:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "=~"
		}
	case 163:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "!~"
		}
	case 164:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = ">"
		}
	case 165:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = ">="
		}
	case 166:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "<"
		}
	case 167:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "<="
		}
	case 168:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Labels = []string{exprDollar[1].str}
		}
	case 169:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Labels = append(exprDollar[1].Labels, exprDollar[3].str)
		}
	case 170:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: exprDollar[3].Labels}
		}
	case 171:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: exprDollar[3].Labels}
		}
	case 172:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: nil}
		}
	case 173:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: nil}
		}
	}
	goto exprstack /* stack new state and value */
}
