// Code generated by goyacc -p expr -o logql/v2/expr.y.go logql/v2/expr.y. DO NOT EDIT.

package v2

import (
	__yyfmt__ "fmt"
	"time"

	"github.com/prometheus/prometheus/model/labels"
)

type exprSymType struct {
	yys                int
	Expr               Expr
	LogBinaryOpExpr    LogBinaryOpExpr
	LogFilterExpr      *LogFilterExpr
	LogLabelFilterExpr *LogLabelFilterExpr
	LogFormatExpr      *LogFormatExpr
	LogQueryExpr       LogSelectorExpr
	LogMetricExpr      LogMetricSampleExpr
	LogNumberExpr      LogNumberExpr
	LogPipelineExpr    LogPipelineExpr
	LogStageExpr       LogStageExpr
	LogRangeQueryExpr  LogSelectorExpr
	LogOffsetExpr      *LogOffsetExpr
	Matcher            *labels.Matcher
	Matchers           []*labels.Matcher
	MetricOp           string
	BinaryOpOptions    BinaryOpOptions
	Range              string
	Filter             string
	Selector           []*labels.Matcher
	Grouping           *grouping
	Labels             []string
	str                string
	binaryOp           string
	ComparisonOp       string
	duration           time.Duration
	ConvOp             string
}

const IDENTIFIER = 57346
const STRING = 57347
const RANGE = 57348
const NUMBER = 57349
const DURATION = 57350
const MATCHERS = 57351
const LABELS = 57352
const EQ = 57353
const RE = 57354
const NRE = 57355
const OPEN_BRACE = 57356
const CLOSE_BRACE = 57357
const OPEN_BRACKET = 57358
const CLOSE_BRACKET = 57359
const COMMA = 57360
const DOT = 57361
const OPEN_PARENTHESIS = 57362
const CLOSE_PARENTHESIS = 57363
const COUNT_OVER_TIME = 57364
const RATE = 57365
const RATE_COUNTER = 57366
const SUM = 57367
const AVG = 57368
const MAX = 57369
const MIN = 57370
const COUNT = 57371
const STDDEV = 57372
const STDVAR = 57373
const BOTTOMK = 57374
const TOPK = 57375
const SORT = 57376
const SORT_DESC = 57377
const BYTES_OVER_TIME = 57378
const BYTES_RATE = 57379
const BOOL = 57380
const JSON = 57381
const REGEXP = 57382
const LOGFMT = 57383
const PIPE_MATCH = 57384
const PIPE_EXACT = 57385
const PIPE = 57386
const LINE_FMT = 57387
const LABEL_FMT = 57388
const UNWRAP = 57389
const AVG_OVER_TIME = 57390
const SUM_OVER_TIME = 57391
const MIN_OVER_TIME = 57392
const MAX_OVER_TIME = 57393
const STDVAR_OVER_TIME = 57394
const STDDEV_OVER_TIME = 57395
const QUANTILE_OVER_TIME = 57396
const FIRST_OVER_TIME = 57397
const LAST_OVER_TIME = 57398
const ABSENT_OVER_TIME = 57399
const BY = 57400
const WITHOUT = 57401
const VECTOR = 57402
const LABEL_REPLACE = 57403
const IP = 57404
const UNPACK = 57405
const PATTERN = 57406
const OFFSET = 57407
const BYTES_CONV = 57408
const DURATION_CONV = 57409
const DURATION_SECONDS_CONV = 57410
const ON = 57411
const IGNORING = 57412
const GROUP_LEFT = 57413
const GROUP_RIGHT = 57414
const DECOLORIZE = 57415
const OR = 57416
const AND = 57417
const UNLESS = 57418
const CMP_EQ = 57419
const NEQ = 57420
const LT = 57421
const LTE = 57422
const GT = 57423
const GTE = 57424
const ADD = 57425
const SUB = 57426
const MUL = 57427
const DIV = 57428
const MOD = 57429
const POW = 57430

var exprToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENTIFIER",
	"STRING",
	"RANGE",
	"NUMBER",
	"DURATION",
	"MATCHERS",
	"LABELS",
	"EQ",
	"RE",
	"NRE",
	"OPEN_BRACE",
	"CLOSE_BRACE",
	"OPEN_BRACKET",
	"CLOSE_BRACKET",
	"COMMA",
	"DOT",
	"OPEN_PARENTHESIS",
	"CLOSE_PARENTHESIS",
	"COUNT_OVER_TIME",
	"RATE",
	"RATE_COUNTER",
	"SUM",
	"AVG",
	"MAX",
	"MIN",
	"COUNT",
	"STDDEV",
	"STDVAR",
	"BOTTOMK",
	"TOPK",
	"SORT",
	"SORT_DESC",
	"BYTES_OVER_TIME",
	"BYTES_RATE",
	"BOOL",
	"JSON",
	"REGEXP",
	"LOGFMT",
	"PIPE_MATCH",
	"PIPE_EXACT",
	"PIPE",
	"LINE_FMT",
	"LABEL_FMT",
	"UNWRAP",
	"AVG_OVER_TIME",
	"SUM_OVER_TIME",
	"MIN_OVER_TIME",
	"MAX_OVER_TIME",
	"STDVAR_OVER_TIME",
	"STDDEV_OVER_TIME",
	"QUANTILE_OVER_TIME",
	"FIRST_OVER_TIME",
	"LAST_OVER_TIME",
	"ABSENT_OVER_TIME",
	"BY",
	"WITHOUT",
	"VECTOR",
	"LABEL_REPLACE",
	"IP",
	"UNPACK",
	"PATTERN",
	"OFFSET",
	"BYTES_CONV",
	"DURATION_CONV",
	"DURATION_SECONDS_CONV",
	"ON",
	"IGNORING",
	"GROUP_LEFT",
	"GROUP_RIGHT",
	"DECOLORIZE",
	"OR",
	"AND",
	"UNLESS",
	"CMP_EQ",
	"NEQ",
	"LT",
	"LTE",
	"GT",
	"GTE",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"POW",
}

var exprStatenames = [...]string{}

const exprEofCode = 1
const exprErrCode = 2
const exprInitialStackSize = 16

var exprExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const exprPrivate = 57344

const exprLast = 638

var exprAct = [...]int{
	185, 69, 58, 57, 173, 4, 159, 5, 96, 77,
	7, 111, 3, 50, 67, 117, 2, 47, 48, 49,
	50, 66, 42, 43, 44, 51, 52, 55, 56, 53,
	54, 45, 46, 47, 48, 49, 50, 43, 44, 51,
	52, 55, 56, 53, 54, 45, 46, 47, 48, 49,
	50, 45, 46, 47, 48, 49, 50, 150, 64, 150,
	95, 51, 52, 55, 56, 53, 54, 45, 46, 47,
	48, 49, 50, 243, 113, 80, 114, 187, 121, 115,
	122, 279, 280, 275, 276, 259, 260, 62, 63, 60,
	256, 257, 151, 221, 313, 131, 297, 134, 135, 136,
	137, 138, 139, 140, 141, 142, 143, 144, 145, 146,
	147, 127, 129, 130, 148, 149, 148, 174, 205, 179,
	326, 188, 67, 65, 183, 219, 184, 181, 224, 66,
	14, 322, 64, 70, 71, 192, 8, 174, 15, 16,
	17, 30, 31, 33, 34, 32, 35, 36, 37, 38,
	39, 40, 18, 19, 153, 154, 155, 199, 200, 201,
	325, 62, 63, 60, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 208, 206, 41, 10, 128, 214,
	215, 212, 95, 213, 217, 218, 115, 211, 222, 162,
	164, 165, 302, 284, 236, 235, 107, 65, 229, 231,
	64, 224, 216, 171, 321, 64, 272, 271, 270, 64,
	234, 240, 224, 247, 171, 320, 242, 244, 267, 64,
	95, 95, 241, 248, 68, 187, 249, 246, 250, 62,
	63, 60, 265, 172, 62, 63, 60, 187, 62, 63,
	60, 224, 311, 264, 319, 266, 261, 268, 62, 63,
	60, 95, 237, 108, 307, 251, 163, 168, 169, 166,
	167, 224, 70, 71, 316, 65, 174, 285, 224, 286,
	65, 315, 287, 224, 65, 245, 310, 174, 293, 295,
	239, 180, 299, 301, 65, 223, 11, 224, 64, 209,
	309, 306, 308, 14, 178, 177, 296, 312, 314, 8,
	291, 15, 16, 17, 30, 31, 33, 34, 32, 35,
	36, 37, 38, 39, 40, 18, 19, 62, 63, 60,
	187, 187, 110, 109, 187, 187, 187, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 305, 300, 41,
	10, 298, 294, 292, 224, 290, 318, 258, 132, 133,
	282, 11, 224, 65, 224, 255, 224, 226, 14, 225,
	281, 278, 12, 13, 8, 187, 15, 16, 17, 30,
	31, 33, 34, 32, 35, 36, 37, 38, 39, 40,
	18, 19, 232, 277, 175, 187, 187, 176, 262, 187,
	238, 202, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 230, 189, 41, 10, 186, 198, 197, 170,
	120, 119, 118, 72, 317, 289, 11, 288, 203, 254,
	253, 150, 220, 14, 191, 190, 126, 12, 13, 116,
	204, 15, 16, 17, 30, 31, 33, 34, 32, 35,
	36, 37, 38, 39, 40, 18, 19, 210, 74, 73,
	269, 324, 323, 304, 303, 124, 283, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 274, 123, 41,
	10, 125, 273, 263, 228, 227, 207, 196, 195, 152,
	194, 182, 193, 158, 157, 156, 252, 76, 14, 78,
	160, 233, 12, 13, 8, 106, 15, 16, 17, 30,
	31, 33, 34, 32, 35, 36, 37, 38, 39, 40,
	18, 19, 78, 9, 75, 6, 59, 61, 161, 1,
	0, 0, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 0, 0, 41, 10, 0, 0, 0, 0,
	0, 0, 106, 0, 0, 0, 112, 0, 0, 0,
	0, 0, 0, 14, 0, 0, 0, 12, 13, 116,
	0, 15, 16, 17, 30, 31, 33, 34, 32, 35,
	36, 37, 38, 39, 40, 18, 19, 98, 101, 97,
	79, 0, 0, 103, 105, 100, 0, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 0, 0, 41,
	10, 99, 102, 0, 0, 0, 0, 0, 0, 0,
	0, 104, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 12, 13, 81, 82, 83, 84, 85, 86,
	87, 88, 89, 90, 91, 92, 93, 94,
}

var exprPact = [...]int{
	344, -1000, -52, -1000, -1000, -1000, -1000, 45, 116, 204,
	393, -1000, 442, 441, 485, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 37, 37, 37, 37, 37, 37, 37, 37,
	37, 37, 37, 37, 37, 37, 37, 45, -1000, -1000,
	538, 191, -1000, -1000, -1000, -1000, 302, 301, 539, 392,
	391, 390, 344, -1000, -1000, 453, 411, -1000, 100, 279,
	-1000, 279, 279, 279, 279, 279, 279, 279, 279, 279,
	279, 279, 279, 279, 279, -1000, 41, -1000, -1000, -1000,
	88, 480, 479, 478, -1000, 486, 178, -1000, 389, -1000,
	-1000, 212, 366, 274, 273, 275, 116, -52, 474, 385,
	382, 407, 406, -1000, -1000, 508, -1000, 477, 475, 473,
	472, -38, 388, 387, -16, -16, -68, -68, -75, -75,
	-75, -75, -32, -32, -32, -32, -32, -32, 491, 491,
	491, -1000, 371, -1000, -1000, -1000, -1000, -1000, -1000, 400,
	419, 113, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	471, -1000, 75, 268, 439, 409, -1000, 75, 75, 196,
	45, 119, 404, 72, 264, 338, -1000, -1000, 336, -1000,
	470, 469, -1000, -1000, -1000, -1000, -1000, 381, 361, 403,
	39, 41, 487, 486, 190, -1000, 370, 259, -1000, 75,
	-1000, 201, 52, 254, -1000, -1000, -1000, 45, 206, 192,
	344, -1000, 234, -1000, 482, -1000, -1000, 402, 401, 334,
	19, 326, 14, 225, 400, -1000, -1000, 368, 468, -1000,
	-1000, 75, 211, 75, 197, 75, 444, -1000, 187, 186,
	185, -1000, -1000, 467, 462, 12, 363, 341, 10, 340,
	330, -1000, 451, 172, -1000, 75, -1000, 75, -1000, -1000,
	75, -1000, -1000, 399, 397, 325, 280, 322, 321, 276,
	76, 320, 317, 171, -1000, -1000, -1000, -1000, 449, 448,
	316, 233, -1000, 269, -1000, 255, 221, 73, -1000, 250,
	-1000, 243, -1000, 396, 328, -1000, 223, -1000, 194, -1000,
	-1000, -1000, 183, -1000, 110, -1000, -1000, 447, 446, -1000,
	-1000, -1000, -1000, 139, 99, -1000, -1000,
}

var exprPgo = [...]int{
	0, 519, 580, 518, 15, 517, 0, 7, 516, 8,
	6, 12, 5, 515, 3, 2, 11, 4, 9, 514,
	513, 10, 1, 479,
}

var exprR1 = [...]int{
	0, 1, 4, 4, 4, 4, 11, 11, 11, 14,
	14, 23, 23, 23, 15, 15, 15, 15, 15, 15,
	15, 15, 15, 15, 15, 15, 8, 8, 9, 9,
	9, 9, 9, 10, 10, 10, 10, 17, 16, 16,
	16, 16, 16, 16, 16, 16, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
	12, 12, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 13, 13, 13,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 21, 21, 21, 19, 19, 18, 18, 18,
	18, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 5, 5,
	5, 5, 3, 3, 3, 3, 3, 3, 3, 3,
	6, 6, 22, 22, 22, 22,
}

var exprR2 = [...]int{
	0, 1, 1, 1, 1, 1, 1, 2, 3, 1,
	2, 1, 1, 1, 1, 2, 2, 2, 2, 3,
	6, 3, 3, 3, 2, 3, 2, 5, 3, 6,
	3, 3, 3, 3, 3, 6, 3, 2, 2, 3,
	3, 4, 5, 5, 6, 2, 4, 5, 6, 7,
	7, 8, 5, 6, 5, 4, 6, 7, 8, 7,
	5, 6, 12, 5, 4, 6, 7, 7, 5, 12,
	4, 3, 4, 4, 4, 4, 4, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 1, 2, 2,
	0, 1, 5, 8, 9, 8, 9, 4, 7, 8,
	7, 8, 5, 8, 9, 8, 9, 4, 7, 8,
	7, 8, 3, 3, 3, 1, 3, 3, 3, 3,
	3, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 3, 4, 4, 3, 3,
}

var exprChk = [...]int{
	-1000, -1, -4, -11, -12, -7, -13, -21, 20, -20,
	61, 7, 83, 84, 14, 22, 23, 24, 36, 37,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
	25, 26, 29, 27, 28, 30, 31, 32, 33, 34,
	35, 60, 74, 75, 76, 83, 84, 85, 86, 87,
	88, 77, 78, 81, 82, 79, 80, -14, -15, -8,
	44, -5, 42, 43, 13, 78, -11, -12, 20, -22,
	58, 59, 20, 7, 7, -19, 2, -18, 4, -2,
	38, -2, -2, -2, -2, -2, -2, -2, -2, -2,
	-2, -2, -2, -2, -2, -15, -9, 41, 39, 63,
	47, 40, 64, 45, 73, 46, 4, 5, 62, 21,
	21, -16, 7, -12, -7, -21, 20, -4, 20, 20,
	20, -12, -7, 15, 2, 18, 15, 11, 78, 12,
	13, -4, 69, 70, -4, -4, -4, -4, -4, -4,
	-4, -4, -4, -4, -4, -4, -4, -4, 75, 74,
	18, 4, -23, 66, 67, 68, 5, 5, 5, -10,
	4, -3, 11, 78, 12, 13, 81, 82, 79, 80,
	20, 2, 21, -17, 65, 18, 21, 21, 21, -14,
	6, -21, 7, -12, -7, -6, 21, 4, -6, 21,
	18, 18, -18, 5, 5, 5, 5, 20, 20, -9,
	-9, -9, 20, 18, 11, 5, 62, 5, -22, 21,
	8, -16, -12, -7, -22, -22, 6, -14, -14, 6,
	18, 21, -17, 21, 18, 21, 21, 5, 5, -6,
	21, -6, 21, 4, -10, 5, 4, 62, 20, 21,
	-22, 21, -17, 21, -17, 21, 21, 21, -14, -12,
	-7, 21, 4, 18, 18, 21, 71, 72, 21, 71,
	72, 21, 20, 5, -22, 21, -22, 21, -22, 6,
	21, 21, 21, 5, 5, 71, 72, 20, 20, 71,
	72, 20, 20, 5, 21, -22, -22, -22, 18, 18,
	20, 20, 21, -6, 21, -6, 20, 20, 21, -6,
	21, -6, 21, 5, 5, 21, -6, 21, -6, 21,
	21, 21, -6, 21, -6, 21, 21, 18, 18, 21,
	21, 21, 21, 5, 5, 21, 21,
}

var exprDef = [...]int{
	0, -2, 1, 2, 3, 4, 5, 6, 0, 0,
	0, 87, 0, 0, 0, 121, 122, 123, 124, 125,
	126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
	136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
	146, 147, 90, 90, 90, 90, 90, 90, 90, 90,
	90, 90, 90, 90, 90, 90, 90, 7, 9, 14,
	0, 0, 148, 149, 150, 151, 0, 0, 0, 0,
	0, 0, 0, 88, 89, 0, 0, 115, 0, 0,
	91, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 10, 15, 16, 17, 18,
	0, 0, 0, 0, 24, 0, 0, 26, 0, 8,
	71, 0, 87, 3, 4, 6, 0, 0, 0, 0,
	0, 3, 4, 112, 113, 0, 114, 0, 0, 0,
	0, 72, 0, 0, 73, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 0, 0,
	0, 19, 0, 11, 12, 13, 21, 22, 23, 25,
	0, 0, 152, 153, 154, 155, 156, 157, 158, 159,
	0, 45, 46, 0, 0, 0, 70, 55, 64, 7,
	38, 6, 87, 3, 4, 0, 164, 160, 0, 165,
	0, 0, 116, 117, 118, 119, 120, 0, 0, 30,
	31, 32, 0, 0, 0, 28, 0, 0, 52, 47,
	37, 0, 3, 4, 54, 63, 40, 39, 0, 0,
	0, 60, 0, 68, 0, 162, 163, 0, 0, 0,
	97, 0, 107, 0, 36, 33, 34, 0, 0, 27,
	53, 48, 0, 56, 0, 65, 0, 41, 0, 3,
	4, 61, 161, 0, 0, 92, 0, 0, 102, 0,
	0, 20, 0, 0, 49, 50, 57, 0, 66, 43,
	42, 59, 67, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 29, 51, 58, 44, 0, 0,
	0, 0, 98, 0, 100, 0, 0, 0, 108, 0,
	110, 0, 35, 0, 0, 93, 0, 95, 0, 99,
	101, 103, 0, 105, 0, 109, 111, 0, 0, 94,
	96, 104, 106, 0, 0, 62, 69,
}

var exprTok1 = [...]int{
	1,
}

var exprTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88,
}

var exprTok3 = [...]int{
	0,
}

var exprErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	exprDebug        = 0
	exprErrorVerbose = false
)

type exprLexer interface {
	Lex(lval *exprSymType) int
	Error(s string)
}

type exprParser interface {
	Parse(exprLexer) int
	Lookahead() int
}

type exprParserImpl struct {
	lval  exprSymType
	stack [exprInitialStackSize]exprSymType
	char  int
}

func (p *exprParserImpl) Lookahead() int {
	return p.char
}

func exprNewParser() exprParser {
	return &exprParserImpl{}
}

const exprFlag = -1000

func exprTokname(c int) string {
	if c >= 1 && c-1 < len(exprToknames) {
		if exprToknames[c-1] != "" {
			return exprToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func exprStatname(s int) string {
	if s >= 0 && s < len(exprStatenames) {
		if exprStatenames[s] != "" {
			return exprStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func exprErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !exprErrorVerbose {
		return "syntax error"
	}

	for _, e := range exprErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + exprTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := exprPact[state]
	for tok := TOKSTART; tok-1 < len(exprToknames); tok++ {
		if n := base + tok; n >= 0 && n < exprLast && exprChk[exprAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if exprDef[state] == -2 {
		i := 0
		for exprExca[i] != -1 || exprExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; exprExca[i] >= 0; i += 2 {
			tok := exprExca[i]
			if tok < TOKSTART || exprExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if exprExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += exprTokname(tok)
	}
	return res
}

func exprlex1(lex exprLexer, lval *exprSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = exprTok1[0]
		goto out
	}
	if char < len(exprTok1) {
		token = exprTok1[char]
		goto out
	}
	if char >= exprPrivate {
		if char < exprPrivate+len(exprTok2) {
			token = exprTok2[char-exprPrivate]
			goto out
		}
	}
	for i := 0; i < len(exprTok3); i += 2 {
		token = exprTok3[i+0]
		if token == char {
			token = exprTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = exprTok2[1] /* unknown char */
	}
	if exprDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", exprTokname(token), uint(char))
	}
	return char, token
}

func exprParse(exprlex exprLexer) int {
	return exprNewParser().Parse(exprlex)
}

func (exprrcvr *exprParserImpl) Parse(exprlex exprLexer) int {
	var exprn int
	var exprVAL exprSymType
	var exprDollar []exprSymType
	_ = exprDollar // silence set and not used
	exprS := exprrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	exprstate := 0
	exprrcvr.char = -1
	exprtoken := -1 // exprrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		exprstate = -1
		exprrcvr.char = -1
		exprtoken = -1
	}()
	exprp := -1
	goto exprstack

ret0:
	return 0

ret1:
	return 1

exprstack:
	/* put a state and value onto the stack */
	if exprDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", exprTokname(exprtoken), exprStatname(exprstate))
	}

	exprp++
	if exprp >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprS[exprp] = exprVAL
	exprS[exprp].yys = exprstate

exprnewstate:
	exprn = exprPact[exprstate]
	if exprn <= exprFlag {
		goto exprdefault /* simple state */
	}
	if exprrcvr.char < 0 {
		exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
	}
	exprn += exprtoken
	if exprn < 0 || exprn >= exprLast {
		goto exprdefault
	}
	exprn = exprAct[exprn]
	if exprChk[exprn] == exprtoken { /* valid shift */
		exprrcvr.char = -1
		exprtoken = -1
		exprVAL = exprrcvr.lval
		exprstate = exprn
		if Errflag > 0 {
			Errflag--
		}
		goto exprstack
	}

exprdefault:
	/* default state action */
	exprn = exprDef[exprstate]
	if exprn == -2 {
		if exprrcvr.char < 0 {
			exprrcvr.char, exprtoken = exprlex1(exprlex, &exprrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if exprExca[xi+0] == -1 && exprExca[xi+1] == exprstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			exprn = exprExca[xi+0]
			if exprn < 0 || exprn == exprtoken {
				break
			}
		}
		exprn = exprExca[xi+1]
		if exprn < 0 {
			goto ret0
		}
	}
	if exprn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			exprlex.Error(exprErrorMessage(exprstate, exprtoken))
			Nerrs++
			if exprDebug >= 1 {
				__yyfmt__.Printf("%s", exprStatname(exprstate))
				__yyfmt__.Printf(" saw %s\n", exprTokname(exprtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for exprp >= 0 {
				exprn = exprPact[exprS[exprp].yys] + exprErrCode
				if exprn >= 0 && exprn < exprLast {
					exprstate = exprAct[exprn] /* simulate a shift of "error" */
					if exprChk[exprstate] == exprErrCode {
						goto exprstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if exprDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", exprS[exprp].yys)
				}
				exprp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if exprDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", exprTokname(exprtoken))
			}
			if exprtoken == exprEofCode {
				goto ret1
			}
			exprrcvr.char = -1
			exprtoken = -1
			goto exprnewstate /* try again in the same state */
		}
	}

	/* reduction by production exprn */
	if exprDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", exprn, exprStatname(exprstate))
	}

	exprnt := exprn
	exprpt := exprp
	_ = exprpt // guard against "declared and not used"

	exprp -= exprR2[exprn]
	// exprp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if exprp+1 >= len(exprS) {
		nyys := make([]exprSymType, len(exprS)*2)
		copy(nyys, exprS)
		exprS = nyys
	}
	exprVAL = exprS[exprp+1]

	/* consult goto table to find next state */
	exprn = exprR1[exprn]
	exprg := exprPgo[exprn]
	exprj := exprg + exprS[exprp].yys + 1

	if exprj >= exprLast {
		exprstate = exprAct[exprg]
	} else {
		exprstate = exprAct[exprj]
		if exprChk[exprstate] != -exprn {
			exprstate = exprAct[exprg]
		}
	}
	// dummy call; replaced with literal code
	switch exprnt {

	case 1:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprlex.(*parser).expr = exprDollar[1].Expr
		}
	case 2:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogQueryExpr
		}
	case 3:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogMetricExpr
		}
	case 4:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogBinaryOpExpr
		}
	case 5:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Expr = exprDollar[1].LogNumberExpr
		}
	case 6:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogQueryExpr = newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), nil)
		}
	case 7:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogQueryExpr = newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[2].LogPipelineExpr)
		}
	case 8:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogQueryExpr = exprDollar[2].LogQueryExpr
		}
	case 9:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogPipelineExpr = LogPipelineExpr{exprDollar[1].LogStageExpr}
		}
	case 10:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogPipelineExpr = append(exprDollar[1].LogPipelineExpr, exprDollar[2].LogStageExpr)
		}
	case 11:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvBytes
		}
	case 12:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDuration
		}
	case 13:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ConvOp = OpConvDurationSeconds
		}
	case 14:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[1].LogFilterExpr
		}
	case 15:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[2].LogLabelFilterExpr
		}
	case 16:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserLogFMT, "", "")
		}
	case 17:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserJSON, "", "")
		}
	case 18:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnpack, "", "")
		}
	case 19:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnwrap, exprDollar[3].str, "")
		}
	case 20:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserUnwrap, exprDollar[5].str, exprDollar[3].ConvOp)
		}
	case 21:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserRegExp, exprDollar[3].str, "")
		}
	case 22:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserPattern, exprDollar[3].str, "")
		}
	case 23:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogParserExpr(ParserLineFormat, exprDollar[3].str, "")
		}
	case 24:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogStageExpr = newLogDecolorizeExpr()
		}
	case 25:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogStageExpr = exprDollar[3].LogFormatExpr
		}
	case 26:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogFilterExpr = newLogFilterExpr(exprDollar[1].Filter, "", exprDollar[2].str)
		}
	case 27:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogFilterExpr = newLogFilterExpr(exprDollar[1].Filter, OpIP, exprDollar[4].str)
		}
	case 28:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = newLogLabelFilter(exprDollar[1].str, exprDollar[2].ComparisonOp, "", exprDollar[3].str)
		}
	case 29:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = newLogLabelFilter(exprDollar[1].str, exprDollar[2].ComparisonOp, OpIP, exprDollar[5].str)
		}
	case 30:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain("and", exprDollar[3].LogLabelFilterExpr)
		}
	case 31:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain("or", exprDollar[3].LogLabelFilterExpr)
		}
	case 32:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogLabelFilterExpr = exprDollar[1].LogLabelFilterExpr.chain(",", exprDollar[3].LogLabelFilterExpr)
		}
	case 33:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: exprDollar[3].str}}, "")
		}
	case 34:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: exprDollar[3].str, IsIdentifier: true}}, "")
		}
	case 35:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr("", LogFormatValues{exprDollar[1].str: LogFormatValue{Value: OpIP + "(" + exprDollar[5].str + ")"}}, "")
		}
	case 36:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogFormatExpr = newLogFormatExpr(",", mergeLogFormatValues(exprDollar[1].LogFormatExpr.kv, exprDollar[3].LogFormatExpr.kv), "")
		}
	case 37:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogOffsetExpr = newLogOffsetExpr(exprDollar[2].duration)
		}
	case 38:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), nil), exprDollar[2].str, nil, false)
		}
	case 39:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[3].LogPipelineExpr), exprDollar[2].str, nil, false)
		}
	case 40:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[1].Selector), exprDollar[2].LogPipelineExpr), exprDollar[3].str, nil, true)
		}
	case 41:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), nil), exprDollar[3].str, nil, false)
		}
	case 42:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[4].LogPipelineExpr), exprDollar[3].str, nil, false)
		}
	case 43:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[3].LogPipelineExpr), exprDollar[5].str, nil, true)
		}
	case 44:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogRangeQueryExpr = newLogRangeQueryExpr(newLogQueryExpr(newStreamMatcherExpr(exprDollar[2].Selector), exprDollar[4].LogPipelineExpr), exprDollar[3].str, exprDollar[6].Grouping, false)
		}
	case 46:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 47:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, exprDollar[1].MetricOp, "", nil, false, nil, exprDollar[4].LogOffsetExpr)
		}
	case 48:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 49:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 50:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 51:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[5].LogRangeQueryExpr, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[8].Grouping, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 52:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, "", "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 53:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(nil, exprDollar[3].LogRangeQueryExpr, "", "", exprDollar[6].Grouping, false, nil, exprDollar[4].LogOffsetExpr)
		}
	case 54:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 55:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 56:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 57:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 58:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[8].Grouping, false, nil, exprDollar[6].LogOffsetExpr)
		}
	case 59:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[6].LogMetricExpr, nil, exprDollar[1].MetricOp, exprDollar[4].str, exprDollar[2].Grouping, true, nil, nil)
		}
	case 60:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, nil)
		}
	case 61:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogMetricExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, exprDollar[5].LogOffsetExpr)
		}
	case 62:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogMetricExpr, nil, OpLabelReplace, "", nil, false, []string{exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str}, nil)
		}
	case 63:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", exprDollar[5].Grouping, false, nil, nil)
		}
	case 64:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", nil, false, nil, nil)
		}
	case 65:
		exprDollar = exprS[exprpt-6 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, nil, false, nil, nil)
		}
	case 66:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[5].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[3].str, exprDollar[7].Grouping, false, nil, nil)
		}
	case 67:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[6].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, exprDollar[4].str, exprDollar[2].Grouping, true, nil, nil)
		}
	case 68:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[4].LogBinaryOpExpr, nil, exprDollar[1].MetricOp, "", exprDollar[2].Grouping, true, nil, nil)
		}
	case 69:
		exprDollar = exprS[exprpt-12 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(exprDollar[3].LogBinaryOpExpr, nil, OpLabelReplace, "", nil, false, []string{exprDollar[5].str, exprDollar[7].str, exprDollar[9].str, exprDollar[11].str}, nil)
		}
	case 70:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogMetricExpr = newLogMetricExpr(newVectorExpr(exprDollar[3].str), nil, OpTypeVector, "", nil, false, nil, nil)
		}
	case 71:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.LogMetricExpr = exprDollar[2].LogMetricExpr
		}
	case 72:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("or", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 73:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("and", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 74:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("unless", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 75:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("+", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 76:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("-", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 77:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("*", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 78:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("/", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 79:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("%", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 80:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("^", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 81:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("==", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 82:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("!=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 83:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr(">", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 84:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr(">=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 85:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("<", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 86:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.LogBinaryOpExpr = newLogBinaryOpExpr("<=", exprDollar[3].BinaryOpOptions, exprDollar[1].Expr, exprDollar[4].Expr)
		}
	case 87:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[1].str, false)
		}
	case 88:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[2].str, false)
		}
	case 89:
		exprDollar = exprS[exprpt-2 : exprpt+1]
		{
			exprVAL.LogNumberExpr = newLogNumberExpr(exprDollar[2].str, true)
		}
	case 90:
		exprDollar = exprS[exprpt-0 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = BinaryOpOptions{}
		}
	case 91:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = BinaryOpOptions{ReturnBool: true}
		}
	case 92:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels}
		}
	case 93:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption}
		}
	case 94:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 95:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption}
		}
	case 96:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 97:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true}
		}
	case 98:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupLeftOption}
		}
	case 99:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 100:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupRightOption}
		}
	case 101:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.OnOption = OnOption{Enabled: true, GroupingType: GroupRightOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 102:
		exprDollar = exprS[exprpt-5 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels}
		}
	case 103:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption}
		}
	case 104:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 105:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption}
		}
	case 106:
		exprDollar = exprS[exprpt-9 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, Labels: exprDollar[4].Labels, GroupingType: GroupRightOption, IncludeLabels: exprDollar[8].Labels}
		}
	case 107:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true}
		}
	case 108:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupLeftOption}
		}
	case 109:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupLeftOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 110:
		exprDollar = exprS[exprpt-7 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupRightOption}
		}
	case 111:
		exprDollar = exprS[exprpt-8 : exprpt+1]
		{
			exprVAL.BinaryOpOptions = exprDollar[1].BinaryOpOptions
			exprVAL.BinaryOpOptions.IgnoringOption = IgnoringOption{Enabled: true, GroupingType: GroupRightOption, IncludeLabels: exprDollar[7].Labels}
		}
	case 112:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 113:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Selector = exprDollar[2].Matchers
		}
	case 114:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
		}
	case 115:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Matchers = []*labels.Matcher{exprDollar[1].Matcher}
		}
	case 116:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matchers = append(exprDollar[1].Matchers, exprDollar[3].Matcher)
		}
	case 117:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 118:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchNotEqual, exprDollar[1].str, exprDollar[3].str)
		}
	case 119:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 120:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Matcher = newLabelMatcher(labels.MatchNotRegexp, exprDollar[1].str, exprDollar[3].str)
		}
	case 121:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeCount
		}
	case 122:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeRate
		}
	case 123:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeRateCounter
		}
	case 124:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeBytes
		}
	case 125:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeBytesRate
		}
	case 126:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeAvg
		}
	case 127:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeSum
		}
	case 128:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeMin
		}
	case 129:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeMax
		}
	case 130:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeStdvar
		}
	case 131:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeStddev
		}
	case 132:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeQuantile
		}
	case 133:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeFirst
		}
	case 134:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeLast
		}
	case 135:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = RangeOpTypeAbsent
		}
	case 136:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSum
		}
	case 137:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeAvg
		}
	case 138:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeCount
		}
	case 139:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeMax
		}
	case 140:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeMin
		}
	case 141:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeStddev
		}
	case 142:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeStdvar
		}
	case 143:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeBottomK
		}
	case 144:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeTopK
		}
	case 145:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSort
		}
	case 146:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = VectorOpTypeSortDesc
		}
	case 147:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.MetricOp = OpTypeVector
		}
	case 148:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "|~"
		}
	case 149:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "|="
		}
	case 150:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "!~"
		}
	case 151:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Filter = "!="
		}
	case 152:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "="
		}
	case 153:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "!="
		}
	case 154:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "=~"
		}
	case 155:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "!~"
		}
	case 156:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = ">"
		}
	case 157:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = ">="
		}
	case 158:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "<"
		}
	case 159:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.ComparisonOp = "<="
		}
	case 160:
		exprDollar = exprS[exprpt-1 : exprpt+1]
		{
			exprVAL.Labels = []string{exprDollar[1].str}
		}
	case 161:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Labels = append(exprDollar[1].Labels, exprDollar[3].str)
		}
	case 162:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: exprDollar[3].Labels}
		}
	case 163:
		exprDollar = exprS[exprpt-4 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: exprDollar[3].Labels}
		}
	case 164:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: false, groups: nil}
		}
	case 165:
		exprDollar = exprS[exprpt-3 : exprpt+1]
		{
			exprVAL.Grouping = &grouping{without: true, groups: nil}
		}
	}
	goto exprstack /* stack new state and value */
}
