module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

replace (
	go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20200425165423-262c93980547
	google.golang.org/grpc => google.golang.org/grpc v1.27.1
)

require github.com/dexidp/dex v0.0.0-20200512115545-709d4169d646 // cmd/dex
