module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/Djarvur/go-err113 v0.0.0-20200511133814-5174e21577d5 // indirect
	github.com/bombsimon/wsl/v3 v3.1.0 // indirect
	github.com/daixiang0/gci v0.2.4 // indirect
	github.com/denis-tingajkin/go-header v0.3.1 // indirect
	github.com/go-critic/go-critic v0.5.2 // indirect
	github.com/gofrs/flock v0.8.0 // indirect
	github.com/golangci/gocyclo v0.0.0-20180528144436-0a533e8fa43d // indirect
	github.com/golangci/golangci-lint v1.21.0 // cmd/golangci-lint
	github.com/jingyugao/rowserrcheck v0.0.0-20191204022205-72ab7603b68a // indirect
	github.com/jirfag/go-printf-func-name v0.0.0-20191110105641-45db9963cdd3 // indirect
	github.com/kyoh86/exportloopref v0.1.7 // indirect
	github.com/maratori/testpackage v1.0.1 // indirect
	github.com/mattn/go-colorable v0.1.7 // indirect
	github.com/mitchellh/go-ps v1.0.0 // indirect
	github.com/nakabonne/nestif v0.3.0 // indirect
	github.com/nishanths/exhaustive v0.0.0-20200811152831-6cf413ae40e0 // indirect
	github.com/ryancurrah/gomodguard v1.1.0 // indirect
	github.com/ryanrolds/sqlclosecheck v0.3.0 // indirect
	github.com/securego/gosec/v2 v2.4.0 // indirect
	github.com/shazow/go-diff v0.0.0-20160112020656-b6b7b6733b8c // indirect
	github.com/sonatard/noctx v0.0.1 // indirect
	github.com/sourcegraph/go-diff v0.6.0 // indirect
	github.com/spf13/cobra v1.0.0 // indirect
	github.com/spf13/viper v1.7.1 // indirect
	github.com/ssgreg/nlreturn/v2 v2.1.0 // indirect
	github.com/stretchr/testify v1.6.1 // indirect
	github.com/tdakkota/asciicheck v0.0.0-20200416190851-d7f85be797a2 // indirect
	github.com/tetafro/godot v0.4.8 // indirect
	github.com/tommy-muehle/go-mnd v1.3.1-0.20200224220436-e6f9a994e8fa // indirect
	github.com/ultraware/funlen v0.0.3 // indirect
	github.com/uudashr/gocognit v1.0.1 // indirect
	github.com/valyala/quicktemplate v1.6.2 // indirect
	honnef.co/go/tools v0.0.1-2020.1.5 // indirect
	mvdan.cc/gofumpt v0.0.0-20200709182408-4fd085cb6d5f // indirect
)
