module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.15

require (
	github.com/fatih/color v1.9.0 // indirect
	github.com/go-pluto/styx v0.0.0-20200109161911-78a77eb717b4
	github.com/urfave/cli v1.22.4 // indirect
)
