apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
    app.kubernetes.io/version: master-2020-09-04-v0.1.1-131-ga4c5a9c
  name: observatorium-api
  namespace: observatorium
spec:
  ports:
  - name: grpc-public
    port: 8090
    targetPort: 8090
  - name: internal
    port: 8081
    targetPort: 8081
  - name: public
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/instance: observatorium-api
    app.kubernetes.io/name: observatorium-api
