// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package models

import (
	"encoding/json"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for AlertStatusState.
const (
	AlertStatusStateActive      AlertStatusState = "active"
	AlertStatusStateSuppressed  AlertStatusState = "suppressed"
	AlertStatusStateUnprocessed AlertStatusState = "unprocessed"
)

// Defines values for AlertingRuleEvaluatedType.
const (
	Alerting AlertingRuleEvaluatedType = "alerting"
)

// Defines values for LogInstantQueryResponseResultType.
const (
	LogInstantQueryResponseResultTypeMatrix  LogInstantQueryResponseResultType = "matrix"
	LogInstantQueryResponseResultTypeScalar  LogInstantQueryResponseResultType = "scalar"
	LogInstantQueryResponseResultTypeStreams LogInstantQueryResponseResultType = "streams"
	LogInstantQueryResponseResultTypeString  LogInstantQueryResponseResultType = "string"
	LogInstantQueryResponseResultTypeVector  LogInstantQueryResponseResultType = "vector"
)

// Defines values for LogRangeQueryResponseResultType.
const (
	LogRangeQueryResponseResultTypeMatrix LogRangeQueryResponseResultType = "matrix"
)

// Defines values for MetricInstantQueryResponseResultType.
const (
	MetricInstantQueryResponseResultTypeMatrix  MetricInstantQueryResponseResultType = "matrix"
	MetricInstantQueryResponseResultTypeScalar  MetricInstantQueryResponseResultType = "scalar"
	MetricInstantQueryResponseResultTypeStreams MetricInstantQueryResponseResultType = "streams"
	MetricInstantQueryResponseResultTypeString  MetricInstantQueryResponseResultType = "string"
	MetricInstantQueryResponseResultTypeVector  MetricInstantQueryResponseResultType = "vector"
)

// Defines values for MetricRangeQueryResponseResultType.
const (
	MetricRangeQueryResponseResultTypeMatrix MetricRangeQueryResponseResultType = "matrix"
)

// Defines values for RecordingRuleEvaluatedType.
const (
	Recording RecordingRuleEvaluatedType = "recording"
)

// Defines values for SilenceStatusState.
const (
	SilenceStatusStateActive  SilenceStatusState = "active"
	SilenceStatusStateExpired SilenceStatusState = "expired"
	SilenceStatusStatePending SilenceStatusState = "pending"
)

// ActiveAlert defines model for ActiveAlert.
type ActiveAlert struct {
	ActiveAt    string             `json:"activeAt"`
	Annotations *map[string]string `json:"annotations,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`
	State       string             `json:"state"`
	Value       string             `json:"value"`
}

// Alert defines model for Alert.
type Alert struct {
	GeneratorURL *string  `json:"generatorURL,omitempty"`
	Labels       LabelSet `json:"labels"`
}

// AlertStatus defines model for AlertStatus.
type AlertStatus struct {
	InhibitedBy []string         `json:"inhibitedBy"`
	MutedBy     []string         `json:"mutedBy"`
	SilencedBy  []string         `json:"silencedBy"`
	State       AlertStatusState `json:"state"`
}

// AlertStatusState defines model for AlertStatus.State.
type AlertStatusState string

// AlertingRule defines model for AlertingRule.
type AlertingRule struct {
	Alert       string             `json:"alert"`
	Annotations *map[string]string `json:"annotations,omitempty"`
	Expr        string             `json:"expr"`
	For         *string            `json:"for,omitempty"`
	Labels      *map[string]string `json:"labels,omitempty"`
}

// AlertingRuleEvaluated defines model for AlertingRuleEvaluated.
type AlertingRuleEvaluated struct {
	Alerts         *[]ActiveAlert             `json:"alerts,omitempty"`
	Annotations    *map[string]string         `json:"annotations,omitempty"`
	Duration       *float32                   `json:"duration,omitempty"`
	EvaluationTime *float32                   `json:"evaluationTime,omitempty"`
	Health         *string                    `json:"health,omitempty"`
	Labels         *map[string]string         `json:"labels,omitempty"`
	LastError      *string                    `json:"lastError,omitempty"`
	LastEvaluation *string                    `json:"lastEvaluation,omitempty"`
	Name           string                     `json:"name"`
	Query          string                     `json:"query"`
	Type           *AlertingRuleEvaluatedType `json:"type,omitempty"`
}

// AlertingRuleEvaluatedType defines model for AlertingRuleEvaluated.Type.
type AlertingRuleEvaluatedType string

// GettableAlert defines model for GettableAlert.
type GettableAlert struct {
	Annotations  LabelSet    `json:"annotations"`
	EndsAt       time.Time   `json:"endsAt"`
	Fingerprint  string      `json:"fingerprint"`
	GeneratorURL *string     `json:"generatorURL,omitempty"`
	Labels       LabelSet    `json:"labels"`
	Receivers    []Receiver  `json:"receivers"`
	StartsAt     time.Time   `json:"startsAt"`
	Status       AlertStatus `json:"status"`
	UpdatedAt    time.Time   `json:"updatedAt"`
}

// GettableAlerts defines model for GettableAlerts.
type GettableAlerts = []GettableAlert

// GettableSilence defines model for GettableSilence.
type GettableSilence struct {
	Comment   string        `json:"comment"`
	CreatedBy string        `json:"createdBy"`
	EndsAt    time.Time     `json:"endsAt"`
	Id        string        `json:"id"`
	Matchers  Matchers      `json:"matchers"`
	StartsAt  time.Time     `json:"startsAt"`
	Status    SilenceStatus `json:"status"`
	UpdatedAt time.Time     `json:"updatedAt"`
}

// GettableSilences defines model for GettableSilences.
type GettableSilences = []GettableSilence

// InstantVectors defines model for InstantVectors.
type InstantVectors struct {
	Metric map[string]string `json:"metric"`
	Values []ScalarOrString  `json:"values"`
}

// LabelSet defines model for LabelSet.
type LabelSet map[string]string

// LogInstantQueryResponse defines model for LogInstantQueryResponse.
type LogInstantQueryResponse struct {
	Result     []LogInstantQueryResponse_Result_Item `json:"result"`
	ResultType LogInstantQueryResponseResultType     `json:"resultType"`
}

// LogInstantQueryResponse_Result_Item defines model for LogInstantQueryResponse.result.Item.
type LogInstantQueryResponse_Result_Item struct {
	union json.RawMessage
}

// LogInstantQueryResponseResultType defines model for LogInstantQueryResponse.ResultType.
type LogInstantQueryResponseResultType string

// LogRangeQueryResponse defines model for LogRangeQueryResponse.
type LogRangeQueryResponse struct {
	Result     []LogRangeQueryResponse_Result_Item `json:"result"`
	ResultType LogRangeQueryResponseResultType     `json:"resultType"`
}

// LogRangeQueryResponse_Result_Item defines model for LogRangeQueryResponse.result.Item.
type LogRangeQueryResponse_Result_Item struct {
	union json.RawMessage
}

// LogRangeQueryResponseResultType defines model for LogRangeQueryResponse.ResultType.
type LogRangeQueryResponseResultType string

// LogSeriesRequest defines model for LogSeriesRequest.
type LogSeriesRequest struct {
	End   *string  `json:"end,omitempty"`
	Match []string `json:"match[]"`
	Start *string  `json:"start,omitempty"`
}

// Matcher defines model for Matcher.
type Matcher struct {
	IsEqual *bool  `json:"isEqual,omitempty"`
	IsRegex bool   `json:"isRegex"`
	Name    string `json:"name"`
	Value   string `json:"value"`
}

// Matchers defines model for Matchers.
type Matchers = []Matcher

// MetricInstantQueryResponse defines model for MetricInstantQueryResponse.
type MetricInstantQueryResponse struct {
	Result     []MetricInstantQueryResponse_Result_Item `json:"result"`
	ResultType MetricInstantQueryResponseResultType     `json:"resultType"`
}

// MetricInstantQueryResponse_Result_Item defines model for MetricInstantQueryResponse.result.Item.
type MetricInstantQueryResponse_Result_Item struct {
	union json.RawMessage
}

// MetricInstantQueryResponseResultType defines model for MetricInstantQueryResponse.ResultType.
type MetricInstantQueryResponseResultType string

// MetricRangeQueryResponse defines model for MetricRangeQueryResponse.
type MetricRangeQueryResponse struct {
	Result     []MetricRangeQueryResponse_Result_Item `json:"result"`
	ResultType MetricRangeQueryResponseResultType     `json:"resultType"`
}

// MetricRangeQueryResponse_Result_Item defines model for MetricRangeQueryResponse.result.Item.
type MetricRangeQueryResponse_Result_Item struct {
	union json.RawMessage
}

// MetricRangeQueryResponseResultType defines model for MetricRangeQueryResponse.ResultType.
type MetricRangeQueryResponseResultType string

// PostSilenceResponse defines model for PostSilenceResponse.
type PostSilenceResponse struct {
	SilenceID *string `json:"silenceID,omitempty"`
}

// PostableAlert defines model for PostableAlert.
type PostableAlert struct {
	Annotations  *LabelSet  `json:"annotations,omitempty"`
	EndsAt       *time.Time `json:"endsAt,omitempty"`
	GeneratorURL *string    `json:"generatorURL,omitempty"`
	Labels       LabelSet   `json:"labels"`
	StartsAt     *time.Time `json:"startsAt,omitempty"`
}

// PostableAlerts defines model for PostableAlerts.
type PostableAlerts = []PostableAlert

// PostableSilence defines model for PostableSilence.
type PostableSilence struct {
	Comment   string    `json:"comment"`
	CreatedBy string    `json:"createdBy"`
	EndsAt    time.Time `json:"endsAt"`
	Id        *string   `json:"id,omitempty"`
	Matchers  Matchers  `json:"matchers"`
	StartsAt  time.Time `json:"startsAt"`
}

// PushLogs defines model for PushLogs.
type PushLogs struct {
	Stream map[string]string `json:"stream"`
	Values []ScalarOrString  `json:"values"`
}

// RangeVectors defines model for RangeVectors.
type RangeVectors struct {
	Metric map[string]string `json:"metric"`
	Values []ScalarOrString  `json:"values"`
}

// Receiver defines model for Receiver.
type Receiver struct {
	Name string `json:"name"`
}

// RecordingRule defines model for RecordingRule.
type RecordingRule struct {
	Expr   string             `json:"expr"`
	Labels *map[string]string `json:"labels,omitempty"`
	Record string             `json:"record"`
}

// RecordingRuleEvaluated defines model for RecordingRuleEvaluated.
type RecordingRuleEvaluated struct {
	EvaluationTime *float32                    `json:"evaluationTime,omitempty"`
	Health         *string                     `json:"health,omitempty"`
	Labels         *map[string]string          `json:"labels,omitempty"`
	LastError      *string                     `json:"lastError,omitempty"`
	LastEvaluation *string                     `json:"lastEvaluation,omitempty"`
	Name           string                      `json:"name"`
	Query          string                      `json:"query"`
	Type           *RecordingRuleEvaluatedType `json:"type,omitempty"`
}

// RecordingRuleEvaluatedType defines model for RecordingRuleEvaluated.Type.
type RecordingRuleEvaluatedType string

// RuleGroup defines model for RuleGroup.
type RuleGroup struct {
	Interval *float32               `json:"interval,omitempty"`
	Name     string                 `json:"name"`
	Rules    []RuleGroup_Rules_Item `json:"rules"`
}

// RuleGroup_Rules_Item defines model for RuleGroup.rules.Item.
type RuleGroup_Rules_Item struct {
	union json.RawMessage
}

// RuleGroupEvaluated defines model for RuleGroupEvaluated.
type RuleGroupEvaluated struct {
	EvaluationTime          *float32                        `json:"evaluationTime,omitempty"`
	File                    *string                         `json:"file,omitempty"`
	Interval                *float32                        `json:"interval,omitempty"`
	LastEvaluation          *string                         `json:"lastEvaluation,omitempty"`
	Limit                   *float32                        `json:"limit,omitempty"`
	Name                    string                          `json:"name"`
	PartialResponseStrategy *string                         `json:"partialResponseStrategy,omitempty"`
	Rules                   []RuleGroupEvaluated_Rules_Item `json:"rules"`
}

// RuleGroupEvaluated_Rules_Item defines model for RuleGroupEvaluated.rules.Item.
type RuleGroupEvaluated_Rules_Item struct {
	union json.RawMessage
}

// Rules defines model for Rules.
type Rules struct {
	Groups []RuleGroupEvaluated `json:"groups"`
}

// RulesRaw defines model for RulesRaw.
type RulesRaw struct {
	Groups []RuleGroup `json:"groups"`
}

// ScalarOrString defines model for ScalarOrString.
type ScalarOrString = []ScalarOrString_Item

// ScalarOrString0 defines model for .
type ScalarOrString0 = string

// ScalarOrString1 defines model for .
type ScalarOrString1 = string

// ScalarOrString_Item defines model for ScalarOrString.Item.
type ScalarOrString_Item struct {
	union json.RawMessage
}

// Silence defines model for Silence.
type Silence struct {
	Comment   string    `json:"comment"`
	CreatedBy string    `json:"createdBy"`
	EndsAt    time.Time `json:"endsAt"`
	Matchers  Matchers  `json:"matchers"`
	StartsAt  time.Time `json:"startsAt"`
}

// SilenceStatus defines model for SilenceStatus.
type SilenceStatus struct {
	State SilenceStatusState `json:"state"`
}

// SilenceStatusState defines model for SilenceStatus.State.
type SilenceStatusState string

// StreamValues defines model for StreamValues.
type StreamValues struct {
	Stream map[string]string `json:"stream"`
	Values []ScalarOrString  `json:"values"`
}

// TailLogs defines model for TailLogs.
type TailLogs struct {
	Labels    map[string]string `json:"labels"`
	Timestamp string            `json:"timestamp"`
}

// AsRangeVectors returns the union data inside the LogInstantQueryResponse_Result_Item as a RangeVectors
func (t LogInstantQueryResponse_Result_Item) AsRangeVectors() (RangeVectors, error) {
	var body RangeVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRangeVectors overwrites any union data inside the LogInstantQueryResponse_Result_Item as the provided RangeVectors
func (t *LogInstantQueryResponse_Result_Item) FromRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRangeVectors performs a merge with any union data inside the LogInstantQueryResponse_Result_Item, using the provided RangeVectors
func (t *LogInstantQueryResponse_Result_Item) MergeRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstantVectors returns the union data inside the LogInstantQueryResponse_Result_Item as a InstantVectors
func (t LogInstantQueryResponse_Result_Item) AsInstantVectors() (InstantVectors, error) {
	var body InstantVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstantVectors overwrites any union data inside the LogInstantQueryResponse_Result_Item as the provided InstantVectors
func (t *LogInstantQueryResponse_Result_Item) FromInstantVectors(v InstantVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstantVectors performs a merge with any union data inside the LogInstantQueryResponse_Result_Item, using the provided InstantVectors
func (t *LogInstantQueryResponse_Result_Item) MergeInstantVectors(v InstantVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScalarOrString returns the union data inside the LogInstantQueryResponse_Result_Item as a ScalarOrString
func (t LogInstantQueryResponse_Result_Item) AsScalarOrString() (ScalarOrString, error) {
	var body ScalarOrString
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScalarOrString overwrites any union data inside the LogInstantQueryResponse_Result_Item as the provided ScalarOrString
func (t *LogInstantQueryResponse_Result_Item) FromScalarOrString(v ScalarOrString) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScalarOrString performs a merge with any union data inside the LogInstantQueryResponse_Result_Item, using the provided ScalarOrString
func (t *LogInstantQueryResponse_Result_Item) MergeScalarOrString(v ScalarOrString) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamValues returns the union data inside the LogInstantQueryResponse_Result_Item as a StreamValues
func (t LogInstantQueryResponse_Result_Item) AsStreamValues() (StreamValues, error) {
	var body StreamValues
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamValues overwrites any union data inside the LogInstantQueryResponse_Result_Item as the provided StreamValues
func (t *LogInstantQueryResponse_Result_Item) FromStreamValues(v StreamValues) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamValues performs a merge with any union data inside the LogInstantQueryResponse_Result_Item, using the provided StreamValues
func (t *LogInstantQueryResponse_Result_Item) MergeStreamValues(v StreamValues) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LogInstantQueryResponse_Result_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LogInstantQueryResponse_Result_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRangeVectors returns the union data inside the LogRangeQueryResponse_Result_Item as a RangeVectors
func (t LogRangeQueryResponse_Result_Item) AsRangeVectors() (RangeVectors, error) {
	var body RangeVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRangeVectors overwrites any union data inside the LogRangeQueryResponse_Result_Item as the provided RangeVectors
func (t *LogRangeQueryResponse_Result_Item) FromRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRangeVectors performs a merge with any union data inside the LogRangeQueryResponse_Result_Item, using the provided RangeVectors
func (t *LogRangeQueryResponse_Result_Item) MergeRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LogRangeQueryResponse_Result_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LogRangeQueryResponse_Result_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRangeVectors returns the union data inside the MetricInstantQueryResponse_Result_Item as a RangeVectors
func (t MetricInstantQueryResponse_Result_Item) AsRangeVectors() (RangeVectors, error) {
	var body RangeVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRangeVectors overwrites any union data inside the MetricInstantQueryResponse_Result_Item as the provided RangeVectors
func (t *MetricInstantQueryResponse_Result_Item) FromRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRangeVectors performs a merge with any union data inside the MetricInstantQueryResponse_Result_Item, using the provided RangeVectors
func (t *MetricInstantQueryResponse_Result_Item) MergeRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsInstantVectors returns the union data inside the MetricInstantQueryResponse_Result_Item as a InstantVectors
func (t MetricInstantQueryResponse_Result_Item) AsInstantVectors() (InstantVectors, error) {
	var body InstantVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromInstantVectors overwrites any union data inside the MetricInstantQueryResponse_Result_Item as the provided InstantVectors
func (t *MetricInstantQueryResponse_Result_Item) FromInstantVectors(v InstantVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeInstantVectors performs a merge with any union data inside the MetricInstantQueryResponse_Result_Item, using the provided InstantVectors
func (t *MetricInstantQueryResponse_Result_Item) MergeInstantVectors(v InstantVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScalarOrString returns the union data inside the MetricInstantQueryResponse_Result_Item as a ScalarOrString
func (t MetricInstantQueryResponse_Result_Item) AsScalarOrString() (ScalarOrString, error) {
	var body ScalarOrString
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScalarOrString overwrites any union data inside the MetricInstantQueryResponse_Result_Item as the provided ScalarOrString
func (t *MetricInstantQueryResponse_Result_Item) FromScalarOrString(v ScalarOrString) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScalarOrString performs a merge with any union data inside the MetricInstantQueryResponse_Result_Item, using the provided ScalarOrString
func (t *MetricInstantQueryResponse_Result_Item) MergeScalarOrString(v ScalarOrString) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamValues returns the union data inside the MetricInstantQueryResponse_Result_Item as a StreamValues
func (t MetricInstantQueryResponse_Result_Item) AsStreamValues() (StreamValues, error) {
	var body StreamValues
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamValues overwrites any union data inside the MetricInstantQueryResponse_Result_Item as the provided StreamValues
func (t *MetricInstantQueryResponse_Result_Item) FromStreamValues(v StreamValues) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamValues performs a merge with any union data inside the MetricInstantQueryResponse_Result_Item, using the provided StreamValues
func (t *MetricInstantQueryResponse_Result_Item) MergeStreamValues(v StreamValues) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MetricInstantQueryResponse_Result_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MetricInstantQueryResponse_Result_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRangeVectors returns the union data inside the MetricRangeQueryResponse_Result_Item as a RangeVectors
func (t MetricRangeQueryResponse_Result_Item) AsRangeVectors() (RangeVectors, error) {
	var body RangeVectors
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRangeVectors overwrites any union data inside the MetricRangeQueryResponse_Result_Item as the provided RangeVectors
func (t *MetricRangeQueryResponse_Result_Item) FromRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRangeVectors performs a merge with any union data inside the MetricRangeQueryResponse_Result_Item, using the provided RangeVectors
func (t *MetricRangeQueryResponse_Result_Item) MergeRangeVectors(v RangeVectors) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t MetricRangeQueryResponse_Result_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *MetricRangeQueryResponse_Result_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRecordingRule returns the union data inside the RuleGroup_Rules_Item as a RecordingRule
func (t RuleGroup_Rules_Item) AsRecordingRule() (RecordingRule, error) {
	var body RecordingRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecordingRule overwrites any union data inside the RuleGroup_Rules_Item as the provided RecordingRule
func (t *RuleGroup_Rules_Item) FromRecordingRule(v RecordingRule) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecordingRule performs a merge with any union data inside the RuleGroup_Rules_Item, using the provided RecordingRule
func (t *RuleGroup_Rules_Item) MergeRecordingRule(v RecordingRule) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlertingRule returns the union data inside the RuleGroup_Rules_Item as a AlertingRule
func (t RuleGroup_Rules_Item) AsAlertingRule() (AlertingRule, error) {
	var body AlertingRule
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlertingRule overwrites any union data inside the RuleGroup_Rules_Item as the provided AlertingRule
func (t *RuleGroup_Rules_Item) FromAlertingRule(v AlertingRule) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlertingRule performs a merge with any union data inside the RuleGroup_Rules_Item, using the provided AlertingRule
func (t *RuleGroup_Rules_Item) MergeAlertingRule(v AlertingRule) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RuleGroup_Rules_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RuleGroup_Rules_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRecordingRuleEvaluated returns the union data inside the RuleGroupEvaluated_Rules_Item as a RecordingRuleEvaluated
func (t RuleGroupEvaluated_Rules_Item) AsRecordingRuleEvaluated() (RecordingRuleEvaluated, error) {
	var body RecordingRuleEvaluated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRecordingRuleEvaluated overwrites any union data inside the RuleGroupEvaluated_Rules_Item as the provided RecordingRuleEvaluated
func (t *RuleGroupEvaluated_Rules_Item) FromRecordingRuleEvaluated(v RecordingRuleEvaluated) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRecordingRuleEvaluated performs a merge with any union data inside the RuleGroupEvaluated_Rules_Item, using the provided RecordingRuleEvaluated
func (t *RuleGroupEvaluated_Rules_Item) MergeRecordingRuleEvaluated(v RecordingRuleEvaluated) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAlertingRuleEvaluated returns the union data inside the RuleGroupEvaluated_Rules_Item as a AlertingRuleEvaluated
func (t RuleGroupEvaluated_Rules_Item) AsAlertingRuleEvaluated() (AlertingRuleEvaluated, error) {
	var body AlertingRuleEvaluated
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAlertingRuleEvaluated overwrites any union data inside the RuleGroupEvaluated_Rules_Item as the provided AlertingRuleEvaluated
func (t *RuleGroupEvaluated_Rules_Item) FromAlertingRuleEvaluated(v AlertingRuleEvaluated) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAlertingRuleEvaluated performs a merge with any union data inside the RuleGroupEvaluated_Rules_Item, using the provided AlertingRuleEvaluated
func (t *RuleGroupEvaluated_Rules_Item) MergeAlertingRuleEvaluated(v AlertingRuleEvaluated) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RuleGroupEvaluated_Rules_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RuleGroupEvaluated_Rules_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsScalarOrString0 returns the union data inside the ScalarOrString_Item as a ScalarOrString0
func (t ScalarOrString_Item) AsScalarOrString0() (ScalarOrString0, error) {
	var body ScalarOrString0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScalarOrString0 overwrites any union data inside the ScalarOrString_Item as the provided ScalarOrString0
func (t *ScalarOrString_Item) FromScalarOrString0(v ScalarOrString0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScalarOrString0 performs a merge with any union data inside the ScalarOrString_Item, using the provided ScalarOrString0
func (t *ScalarOrString_Item) MergeScalarOrString0(v ScalarOrString0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScalarOrString1 returns the union data inside the ScalarOrString_Item as a ScalarOrString1
func (t ScalarOrString_Item) AsScalarOrString1() (ScalarOrString1, error) {
	var body ScalarOrString1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScalarOrString1 overwrites any union data inside the ScalarOrString_Item as the provided ScalarOrString1
func (t *ScalarOrString_Item) FromScalarOrString1(v ScalarOrString1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScalarOrString1 performs a merge with any union data inside the ScalarOrString_Item, using the provided ScalarOrString1
func (t *ScalarOrString_Item) MergeScalarOrString1(v ScalarOrString1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ScalarOrString_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ScalarOrString_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
