components:
  parameters:
    tenant:
      in: path
      name: tenant
      description: name of the tenant
      required: true
      schema:
        type: string
    seriesMatcher:
      in: query
      name: match[]
      description: Repeated series selector argument
      required: true
      schema:
        type: array
        items:
          type: string
    optionalSeriesMatcher:
      in: query
      name: match[]
      description: Repeated series selector argument
      schema:
        type: array
        items:
          type: string
    startTS:
      in: query
      name: start
      description: Start timestamp
      schema:
        type: string
        format: rfc3339 | unix_timestamp
    endTS:
      in: query
      name: end
      description: End timestamp
      schema:
        type: string
        format: rfc3339 | unix_timestamp
    promqlQuery:
      in: query
      name: query
      description: PromQL query to fetch result for metrics
      schema:
        type: string
    logqlQuery:
      in: query
      name: query
      description: LogQL query to fetch result for logs
      schema:
        type: string
    queryTimeout:
      in: query
      name: timeout
      description: Evaluation timeout
      schema:
        type: string
    limit:
      in: query
      name: limit
      description: Max number of entries 
      schema:
        type: number
    queryDedup:
      in: query
      name: dedup
      description: Query deduplication (Thanos)
      schema:
        type: boolean
    queryPartialResponse:
      in: query
      name: partial_response
      description: Query partial response (Thanos)
      schema:
        type: boolean
    logRulesNamespace:
      in: path
      name: namespace
      description: namespace of the log rule group
      required: true
      schema:
        type: string
    logRulesGroup:
      in: path
      name: group
      description: group of the log rule
      required: true
      schema:
        type: string
