// Package responses provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package responses

import (
	externalRef0 "github.com/observatorium/api/client/models"
)

// AllLogRulesResponse defines model for AllLogRulesResponse.
type AllLogRulesResponse map[string]interface{}

// LogLabelValuesResponse defines model for LogLabelValuesResponse.
type LogLabelValuesResponse struct {
	Data      []string  `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}

// LogLabelsResponse defines model for LogLabelsResponse.
type LogLabelsResponse struct {
	Data      []string  `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}

// LogQueryRangeResponse defines model for LogQueryRangeResponse.
type LogQueryRangeResponse struct {
	Data      externalRef0.LogRangeQueryResponse `json:"data"`
	Error     *string                            `json:"error,omitempty"`
	ErrorType *string                            `json:"errorType,omitempty"`
	Status    string                             `json:"status"`
	Warnings  *[]string                          `json:"warnings,omitempty"`
}

// LogQueryResponse defines model for LogQueryResponse.
type LogQueryResponse struct {
	Data      externalRef0.LogInstantQueryResponse `json:"data"`
	Error     *string                              `json:"error,omitempty"`
	ErrorType *string                              `json:"errorType,omitempty"`
	Status    string                               `json:"status"`
	Warnings  *[]string                            `json:"warnings,omitempty"`
}

// LogReadResponse defines model for LogReadResponse.
type LogReadResponse struct {
	DroppedEntries *[]externalRef0.TailLogs `json:"dropped_entries,omitempty"`
	Error          *string                  `json:"error,omitempty"`
	ErrorType      *string                  `json:"errorType,omitempty"`
	Items          *string                  `json:"items,omitempty"`
	Status         string                   `json:"status"`
	Streams        []externalRef0.PushLogs  `json:"streams"`
	Warnings       *[]interface{}           `json:"warnings,omitempty"`
}

// LogRulesGroupResponse defines model for LogRulesGroupResponse.
type LogRulesGroupResponse struct {
	Interval *string                 `json:"interval,omitempty"`
	Name     string                  `json:"name"`
	Rules    []externalRef0.RulesRaw `json:"rules"`
}

// LogRulesNamespaceResponse defines model for LogRulesNamespaceResponse.
type LogRulesNamespaceResponse struct {
	Groups []externalRef0.RuleGroup `json:"groups"`
}

// LogRulesPrometheusResponse defines model for LogRulesPrometheusResponse.
type LogRulesPrometheusResponse struct {
	Data      externalRef0.Rules `json:"data"`
	Error     *string            `json:"error,omitempty"`
	ErrorType *string            `json:"errorType,omitempty"`
	Status    string             `json:"status"`
	Warnings  *[]string          `json:"warnings,omitempty"`
}

// LogSeriesResponse defines model for LogSeriesResponse.
type LogSeriesResponse struct {
	Data []struct {
		AdditionalProperties map[string]string `json:"-"`
	} `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}

// LogWriteResponse defines model for LogWriteResponse.
type LogWriteResponse struct {
	Error     *string                 `json:"error,omitempty"`
	ErrorType *string                 `json:"errorType,omitempty"`
	Status    string                  `json:"status"`
	Streams   []externalRef0.PushLogs `json:"streams"`
	Warnings  *[]string               `json:"warnings,omitempty"`
}

// MetricLabelValuesResponse defines model for MetricLabelValuesResponse.
type MetricLabelValuesResponse struct {
	Data      []string  `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}

// MetricLabelsResponse defines model for MetricLabelsResponse.
type MetricLabelsResponse struct {
	Data      []string  `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}

// MetricQueryRangeResponse defines model for MetricQueryRangeResponse.
type MetricQueryRangeResponse struct {
	Data      externalRef0.MetricRangeQueryResponse `json:"data"`
	Error     *string                               `json:"error,omitempty"`
	ErrorType *string                               `json:"errorType,omitempty"`
	Status    string                                `json:"status"`
	Warnings  *[]string                             `json:"warnings,omitempty"`
}

// MetricQueryResponse defines model for MetricQueryResponse.
type MetricQueryResponse struct {
	Data      externalRef0.MetricInstantQueryResponse `json:"data"`
	Error     *string                                 `json:"error,omitempty"`
	ErrorType *string                                 `json:"errorType,omitempty"`
	Status    string                                  `json:"status"`
	Warnings  *[]string                               `json:"warnings,omitempty"`
}

// MetricRulesResponse defines model for MetricRulesResponse.
type MetricRulesResponse struct {
	Data      externalRef0.Rules `json:"data"`
	Error     *string            `json:"error,omitempty"`
	ErrorType *string            `json:"errorType,omitempty"`
	Status    string             `json:"status"`
	Warnings  *[]string          `json:"warnings,omitempty"`
}

// MetricSeriesResponse defines model for MetricSeriesResponse.
type MetricSeriesResponse struct {
	Data []struct {
		AdditionalProperties map[string]string `json:"-"`
	} `json:"data"`
	Error     *string   `json:"error,omitempty"`
	ErrorType *string   `json:"errorType,omitempty"`
	Status    string    `json:"status"`
	Warnings  *[]string `json:"warnings,omitempty"`
}
