apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: query-user-cert
  namespace: proxy
spec:
  secretName: query-user-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: query@example.com
  dnsNames:
  - query@example.com
  subject:
    organizationalUnits:
    - "query-users"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: write-user-cert
  namespace: proxy
spec:
  secretName: write-user-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: write@example.com
  dnsNames:
  - write@example.com
  subject:
    organizationalUnits:
    - "write-users"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: logs-reader-cert
  namespace: proxy
spec:
  secretName: logs-reader-cert
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
  commonName: logs-reader@example.com
  dnsNames:
  - logs-reader@example.com
  subject:
    organizationalUnits:
    - "logs-readers"